### ISSUE TITLE
Logging is blocked when pytuya is imported

### ISSUE THREAD

**Issue by ghost** [clach04/python-tuya#47]
Pytuya is a part of my Snips Homeautomation.
I tried to implement logging for several times now and today I found out that the pytuya module somehow blocks logging. 

Here is a simple example to reproduce the problem:

```
import pytuya
import logging

logging.basicConfig(
        level=logging.INFO,
        filename='logs.log',
        filemode='w'
)

logger = logging.getLogger('Test')
logger.addHandler(logging.StreamHandler())
logger.info('Test')

```
is not working.

```
#import pytuya
import logging

logging.basicConfig(
        level=logging.INFO,
        filename='logs.log',
        filemode='w'
)

logger = logging.getLogger('Test')
logger.addHandler(logging.StreamHandler())
logger.info('Test')

```
by commenting the pytuya module the logger is working again...

Is there a simple way to fix that?

Thank you!

**Comment by clach04** [comment]
@LucidSkyWalker I think the issue here is that both the library and your calling app both used basicconfig, and pytuya called it first. One workaround would be to import pytuya *AFTER* you setup logging.

Thanks for reporting this, I think the correct solution is for pytuya to not to setup any config (and then for callers to choose). I'll get that done.
